# TODO: implement NoTTY
NoTTY = false
ConnectionsPerBox = 3 # default to 3
CallBackIps = ["192.168.1.12","hackerbox"] # One will be randomly chosen every time we drop one

[[target]]
Ips = ["127.0.0.1","192.168.140.138","172.17.156.129"]
#Ips = ["172.16.X.3","172.16.X.4","172.16.X.5"]
#ReplaceX = "1-5"
Modules = ["STARFOX",]
Stealthy = true # Optional, will enable log deletion/cleanup/avoidance of noisy techs
Annoying = true # Optional, will enable troll/annoying actions
Level = 1   # "Difficulty" level, default 0. Range 0-5 where lower is more difficult
Username = ["root", "hiro"] # user must be root or a sudoer
Password = ["Password1!", "CyberCringe3!"]

[[target]]
Ips = ["10.20.X.11","10.20.X10.13"]
ReplaceX = "3-5" # if you have an X in the above, iterate through range here
Modules = ["ireul",]
Username = ["root", "vpxuser", "dcui"]
Password = ["Password1!",]

[[module]]
Name = "STARFOX"
#Debug = true
#Enabled = ["vim_troll",]

[[module]]
Name = "ireul"
